version: "3.8"

services:

  storage:
    image: marcinkulik/storage-for-numbers:v2
    ports:
      - "5010:5010"
    healthcheck:
      test: curl --fail -s http://localhost:5010/alive || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  rest-api:
    build: .
    restart: on-failure
    ports:
      - "5000:5000"
    depends_on:
      - storage
    links:
      - storage
    healthcheck:
      test: curl --fail -s http://localhost:5000/alive || exit 1
      interval: 30s
      timeout: 10s
      retries: 5


